@echo off
start /d "C:\Program Files (x86)\Google\Chrome\Application" chrome.exe https://uat.proformprofessionals.com
start /d "C:\Program Files (x86)\Google\Chrome\Application" chrome.exe https://csgsol-uat.proformprofessionals.com
start /d "C:\Program Files (x86)\Google\Chrome\Application" chrome.exe https://uat-oauth.proformprofessionals.com/login
start /d "C:\Program Files (x86)\Google\Chrome\Application" chrome.exe https://uat-oauth.proformprofessionals.com/auth/test
start /d "C:\Program Files (x86)\Google\Chrome\Application" chrome.exe https://montgomerycountymd-uat.proformprofessionals.com
start /d "C:\Program Files (x86)\Google\Chrome\Application" chrome.exe https://ampit-uat.proformprofessionals.com
start /d "C:\Program Files (x86)\Google\Chrome\Application" chrome.exe https://finra-uat.proformprofessionals.com
start /d "C:\Program Files (x86)\Google\Chrome\Application" chrome.exe https://moonitsolutions-uat.proformprofessionals.com
start /d "C:\Program Files (x86)\Google\Chrome\Application" chrome.exe https://csgsol-uat.proformprofessionals.com/thirdparty/test
start /d "C:\Program Files (x86)\Google\Chrome\Application" chrome.exe https://csgsol-uat.proformprofessionals.com/schedular/test
start /d "C:\Program Files (x86)\Google\Chrome\Application" chrome.exe https://uat-geo.proformprofessionals.com/proform-geo-service-3.3/test
start /d "C:\Program Files (x86)\Google\Chrome\Application" chrome.exe https://uat-data.proformprofessionals.com/proform-data-service-3.3/test
start /d "C:\Program Files (x86)\Google\Chrome\Application" chrome.exe https://uat-data.proformprofessionals.com/proform-accounting-service-3.3/test
start /d "C:\Program Files (x86)\Google\Chrome\Application" chrome.exe https://uat-devex.proformprofessionals.com/proform-simulator-service-3.3/test
start /d "C:\Program Files (x86)\Google\Chrome\Application" chrome.exe https://uat-devex.proformprofessionals.com/proform-simulator-rules-service-3.3/test
start /d "C:\Program Files (x86)\Google\Chrome\Application" chrome.exe https://uat-devex-utils.proformprofessionals.com/proform-dev-ex-runner-service-3.3/test
start /d "C:\Program Files (x86)\Google\Chrome\Application" chrome.exe https://uat-apilogs.proformprofessionals.com/test
start /d "C:\Program Files (x86)\Google\Chrome\Application" chrome.exe https://uat-devex2-jp.proformprofessionals.com/status
start /d "C:\Program Files (x86)\Google\Chrome\Application" chrome.exe https://uat-campaign.proformprofessionals.com/status
start /d "C:\Program Files (x86)\Google\Chrome\Application" chrome.exe https://uat-pdfconverter.proformprofessionals.com/api/home/index
start /d "C:\Program Files (x86)\Google\Chrome\Application" chrome.exe https://uat-devex2-csharp.proformprofessionals.com/Home/Index
start /d "C:\Program Files (x86)\Google\Chrome\Application" chrome.exe https://uat-ssapi.proformprofessionals.com/test
start /d "C:\Program Files (x86)\Google\Chrome\Application" chrome.exe https://uat-assessmentlogs.proformprofessionals.com/test
start /d "C:\Program Files (x86)\Google\Chrome\Application" chrome.exe https://dummythirdparty-uat.proformprofessionals.com/dummy/test
start /d "C:\Program Files (x86)\Google\Chrome\Application" chrome.exe https://uat-proformapi.proformprofessionals.com/ping
start /d "C:\Program Files (x86)\Google\Chrome\Application" chrome.exe https://uat-proform-internal.proformprofessionals.com/proform-internal-service-3.3/test
start /d "C:\Program Files (x86)\Google\Chrome\Application" chrome.exe https://uat-license-scheduler.proformprofessionals.com/swagger-ui.html
start /d "C:\Program Files (x86)\Google\Chrome\Application" chrome.exe https://uat-proformlicensing.proformprofessionals.com/home
start /d "C:\Program Files (x86)\Google\Chrome\Application" chrome.exe https://uat-data.proformprofessionals.com/proform-internal-service-3.3/test
