AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  releses3bucket:
    MinLength: '1'
    MaxLength: '50'
    Type: String
    Description: CI/CD Release bucket
    ConstraintDescription: Relese S3 Bucket
  FolderName:
    MinLength: '1'
    MaxLength: '50'
    Type: String
    Description: CI/CD Release ID
    ConstraintDescription: ReleaseID
  Prod:
    MinLength: '1'
    MaxLength: '50'
    Type: String
    Description: Prod OU ID
    ConstraintDescription: Prod OU ID
  NonProd:
    MinLength: '1'
    MaxLength: '50'
    Type: String
    Description: Non Prod OU ID
    ConstraintDescription: Non Prod OU ID
  SharedServices:
    MinLength: '1'
    MaxLength: '50'
    Type: String
    Description: Shared Services OU ID
    ConstraintDescription: Shared Services OU ID
  Exceptions:
    MinLength: '1'
    MaxLength: '50'
    Type: String
    Description: Exceptions OU ID
    ConstraintDescription: Exceptions OU ID
  RESPCMigration:
    MinLength: '1'
    MaxLength: '50'
    Type: String
    Description: RESPCMigration OU ID
    ConstraintDescription: RESPCMigration OU ID
  # CoreOU:
  #   Type: String
  #   Description: Core OU
  platformagentbucket:
    Type: String
    Description: S3 Agent Name
  auditaccount:
    Type: String
    Description: audit account
  masteraccount:
    Type: String
    Description: Master Account
  ScoreCardDBTableName:
    Type: String
    Description: Enter the DPSOM DL Id
  ScoreCardBucketName:
    Type: String
    Description: Enter the ScoreCardBucketName 
  BucketNameWithOutRegion:
    Type: String
    Description: Enter the BucketNameWithOutRegion 
  platformScoreCardFunctionName:
    Type: String
    Description: Enter ScoreCardVPCBoundLamba name

Resources:
  PlatformDBControlsStackset:
    Type: AWS::CloudFormation::StackSet
    DeletionPolicy: Retain
    Properties:
      TemplateURL:
        Fn::Sub:
          - https://${bucket}.s3.amazonaws.com/${releasefolder}/CloudFormation/Stackset_DBCntrols.yaml
          - bucket:
              Ref: releses3bucket
            releasefolder:
              Ref: FolderName
      StackSetName: Nested-OU-Platform-DBControls
      AutoDeployment:
        Enabled: 'true'
        RetainStacksOnAccountRemoval: 'false'
      PermissionModel: SERVICE_MANAGED
      Capabilities:
        - CAPABILITY_NAMED_IAM
      StackInstancesGroup:
        - Regions:
            - us-east-1
          DeploymentTargets:
            OrganizationalUnitIds:
              - !Ref RESPCMigration
              - !Ref Prod
              - !Ref NonProd
              - !Ref SharedServices
              - !Ref Exceptions
              #- !Ref CoreOU
      OperationPreferences:
        RegionConcurrencyType: 'PARALLEL'
        FailureTolerancePercentage: 90
        MaxConcurrentPercentage: 95
      Parameters:
        - ParameterKey: masteraccount
          ParameterValue: !Ref masteraccount
        - ParameterKey: auditaccount
          ParameterValue: !Ref auditaccount
        - ParameterKey: platformagentbucket
          ParameterValue: !Ref platformagentbucket
        - ParameterKey: ScoreCardBucketName
          ParameterValue: !Ref ScoreCardBucketName
        - ParameterKey: S3BucketName
          ParameterValue: !Ref BucketNameWithOutRegion 
        - ParameterKey: FolderName
          ParameterValue: !Ref FolderName  
        - ParameterKey: ScoreCardDBTableName
          ParameterValue: !Ref ScoreCardDBTableName 
        - ParameterKey: platformScoreCardFunctionName
          ParameterValue: !Ref platformScoreCardFunctionName
      Tags:
        - Value: 'yes'
          Key: platform_donotdelete