AWSTemplateFormatVersion: '2010-09-09'
Description: Template to create SGC ServiceNow Graph Connector Documents

Resources:
  #----------------------------SG-AWS-RunShellScript-Setup-----------------------------
  SGAWSRunPowerShellScript:
    Type: AWS::SSM::Document
    Properties: 
      Content:
        {
        "schemaVersion": "2.2",
        "description": "Service Graph AWS - aws:runPowerShellScript",
        "mainSteps": [
          {
            "action": "aws:runPowerShellScript",
            "name": "runPowerShellScript",
            "inputs": {
              "timeoutSeconds": "3600",
              "runCommand": [
                "echo '####SG-AWS-06-02-2022####'",
                "echo '####-WINDOWS-####'",
                "wmic bios get serialnumber | foreach {\"###SERIAL###\"+ $_}",
                "netstat -anop TCP | foreach {\"###TCP###\"+ $_}",
                "cmd /a /c 'wmic computersystem get model,name,systemtype,manufacturer,DNSHostName,domain,TotalPhysicalMemory,NumberOfProcessors /format:list' | foreach {\"###CS###\"+ $_}",
                "cmd /a /c 'wmic cpu get Manufacturer,MaxClockSpeed,DeviceID,Name,Caption /format:list' | foreach {\"###CPU###\"+ $_}",
                "cmd /a /c 'wmic process get ProcessId, ParentProcessId, Name, ExecutablePath, Description, CommandLine /format:rawxml' | foreach {\"###PS###\"+ $_}",
                "(Get-Disk | measure-object -Property size -Sum).Sum / 1GB | foreach {\"###DISK###\"+ $_}",
                "(Get-WmiObject Win32_PhysicalMemory | measure-object Capacity -sum).sum/1gb | foreach {\"###RAM-GB###\"+ $_}"
              ]
            }
          }
        ]
      }
      DocumentFormat: JSON
      DocumentType: Command
      Name: "platform_SG-AWS-RunPowerShellScript"
      Tags: 
      - Key: "platform_donotdelete"
        Value: "yes"

#---------------------------SG-AWS-RunShellScript--------------------------
  SGAWSRunShellScript:
    Type: AWS::SSM::Document
    Properties: 
      Content:
        {
        "schemaVersion": "2.2",
        "description": "Service Graph AWS - aws:runShellScript",
        "mainSteps": [
          {
            "inputs": {
              "timeoutSeconds": "3600",
              "runCommand": [
                "echo '####SG-AWS-06-02-2022####'",
                "dmidecode system | grep -E '(Manufacturer|Product Name|Serial Number)'| sed 's/^/#DMI#/'",
                "ps awwxo pid,ppid,command | sed 's/^/#PS#/'",
                "netstat -anpt | sed 's/^/#NETSTAT#/'",
                "grep -E '(model name|vendor_id|cpu MHz|cpu cores)' /proc/cpuinfo | sed 's/^/#CPU#/'",
                "awk '/MemTotal/ {print $2}' /proc/meminfo | sed 's/^/#RAM-KB#/'",
                "lsblk -dn | grep -v '^loop' | sed 's/^/#DISK#/'"
              ]
            },
            "name": "runShellScript",
            "action": "aws:runShellScript"
          }
        ]
      }
      DocumentFormat: JSON
      DocumentType: Command
      Name: "platform_SG-AWS-RunShellScript"
      Tags: 
      - Key: "platform_donotdelete"
        Value: "yes"
