SERVICES = [
    # AWS
    {"name": "ec2", "description": "AWS EC2 (Elastic Compute Cloud)"},
    {"name": "rds", "description": "AWS RDS (Relational Database Service)"},
    {"name": "s3", "description": "AWS S3 (Simple Storage Service)"},
    {"name": "elb", "description": "AWS ELB (Elastic Load Balancer)"},
    {"name": "lambda", "description": "AWS Lambda (Serverless Functions)"},
    {"name": "dynamodb", "description": "AWS DynamoDB (NoSQL Database)"},
    {"name": "cloudfront", "description": "AWS CloudFront (Content Delivery Network)"},
    {"name": "ecr", "description": "AWS ECR (Elastic Container Registry)"},
    {"name": "ecs", "description": "AWS ECS (Elastic Container Service)"},
    {"name": "sagemaker", "description": "AWS SageMaker (Machine Learning)"},
    {"name": "redshift", "description": "AWS Redshift (Data Warehouse)"},
    {"name": "elasticache", "description": "AWS ElastiCache (In-memory Cache)"},
    {"name": "cloudwatch", "description": "AWS CloudWatch (Monitoring)"},
    {"name": "sns", "description": "AWS SNS (Simple Notification Service)"},
    {"name": "sqs", "description": "AWS SQS (Simple Queue Service)"},
    # Azure
    {"name": "vm", "description": "Azure VM (Virtual Machine)"},
    {"name": "sql", "description": "Azure SQL Database"},
    {"name": "blob", "description": "Azure Blob Storage"},
    {"name": "appsvc", "description": "Azure App Service"},
    {"name": "cosmos", "description": "Azure Cosmos DB"},
    {"name": "aks", "description": "Azure Kubernetes Service (AKS)"},
    {"name": "containerinstance", "description": "Azure Container Instances"},
    {"name": "batch", "description": "Azure Batch (Batch Processing)"},
    {"name": "eventhub", "description": "Azure Event Hub"},
    {"name": "redis", "description": "Azure Cache for Redis"},
    {"name": "monitor", "description": "Azure Monitor"},
    {"name": "storagequeue", "description": "Azure Storage Queue"},
    {"name": "logicapp", "description": "Azure Logic Apps"},
    # GCP
    {"name": "gce", "description": "GCP Compute Engine"},
    {"name": "cloudsql", "description": "GCP Cloud SQL"},
    {"name": "gcs", "description": "GCP Cloud Storage"},
    {"name": "gae", "description": "GCP App Engine"},
    {"name": "bigquery", "description": "GCP BigQuery"},
    {"name": "cloudfunctions", "description": "GCP Cloud Functions"},
    {"name": "pubsub", "description": "GCP Pub/Sub Messaging"},
    {"name": "datastore", "description": "GCP Datastore (NoSQL Database)"},
    {"name": "memorystore", "description": "GCP Memorystore (In-memory Cache)"},
    {"name": "composer", "description": "GCP Composer (Workflow Orchestration)"},
    {"name": "dataproc", "description": "GCP Dataproc (Managed Spark/Hadoop)"},
    {"name": "spanner", "description": "GCP Spanner (Distributed SQL DB)"},
    {"name": "tasks", "description": "GCP Cloud Tasks"},
]

def list_services():
    return SERVICES
