##################################################################################
#
#   
#     Shell custom Conformance Pack around Best Practices for RDS
#     The custome SSM Document for Remidiating the Public Access is Deployed Via DB Controls Stackset
#
##################################################################################
Resources:
  RdsStorageEncrypted:
    Properties:
      ConfigRuleName: rds-storage-encrypted
      Scope:
        ComplianceResourceTypes:
        - AWS::RDS::DBInstance
      Source:
        Owner: AWS
        SourceIdentifier: RDS_STORAGE_ENCRYPTED
    Type: AWS::Config::ConfigRule
  RdsSnapshotEncrypted:
    Properties:
      ConfigRuleName: rds-snapshot-encrypted
      Scope:
        ComplianceResourceTypes:
        - AWS::RDS::DBSnapshot
        - AWS::RDS::DBClusterSnapshot
      Source:
        Owner: AWS
        SourceIdentifier: RDS_SNAPSHOT_ENCRYPTED
    Type: AWS::Config::ConfigRule
  RdsInstancePublicAccessCheck:
    Properties:
      ConfigRuleName: rds-instance-public-access-check
      Scope:
        ComplianceResourceTypes:
        - AWS::RDS::DBInstance
      Source:
        Owner: AWS
        SourceIdentifier: RDS_INSTANCE_PUBLIC_ACCESS_CHECK
    Type: AWS::Config::ConfigRule
  RdsInstancePublicAccessRemediation:
    DependsOn: RdsInstancePublicAccessCheck
    Type: 'AWS::Config::RemediationConfiguration'
    Properties:
      ConfigRuleName: rds-instance-public-access-check
      ResourceType: "AWS::RDS::DBInstance"
      TargetId: "platform_rds_public_access_remediation_with_exception"
      TargetType: "SSM_DOCUMENT"
      TargetVersion: "1"
      Parameters:
        AutomationAssumeRole:
          StaticValue:
            Values: 
            - arn:aws:iam::364355817034:role/platform_rds_compliance_remediation_role_us-east-1
        DbiResourceId:
          ResourceValue:
            Value: RESOURCE_ID
      ExecutionControls:
        SsmControls:
          ConcurrentExecutionRatePercentage: 10
          ErrorPercentage: 10
      Automatic: True
      MaximumAutomaticAttempts: 10
      RetryAttemptSeconds: 600
  RdsSnapshotsPublicProhibited:
    Properties:
      ConfigRuleName: rds-snapshots-public-prohibited
      Scope:
        ComplianceResourceTypes:
        - AWS::RDS::DBSnapshot
        - AWS::RDS::DBClusterSnapshot
      Source:
        Owner: AWS
        SourceIdentifier: RDS_SNAPSHOTS_PUBLIC_PROHIBITED
    Type: AWS::Config::ConfigRule
  RdsVPCGroup:
    Properties:
      ConfigRuleName: shell-rds-instance-in-vpc-check
      Scope:
        ComplianceResourceTypes:
        - AWS::RDS::DBInstance
      Source:
        Owner: CUSTOM_POLICY
        SourceDetails:
          -
            EventSource: aws.config
            MessageType: ConfigurationItemChangeNotification
        CustomPolicyDetails:
          PolicyRuntime: guard-2.x.x
          PolicyText: rule check_rds_vpc {configuration.DBSubnetGroup.VpcId !exists}
          EnableDebugLogDelivery: true
    Type: AWS::Config::ConfigRule