AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  releses3bucket:
    MinLength: '1'
    MaxLength: '50'
    Type: String
    Description: CI/CD Release bucket
    ConstraintDescription: Relese S3 Bucket
  FolderName:
    MinLength: '1'
    MaxLength: '50'
    Type: String
    Description: CI/CD Release ID
    ConstraintDescription: ReleaseID
  Prod:
    MinLength: '1'
    MaxLength: '50'
    Type: String
    Description: Prod OU ID
    ConstraintDescription: Prod OU ID
  NonProd:
    MinLength: '1'
    MaxLength: '50'
    Type: String
    Description: Non Prod OU ID
    ConstraintDescription: Non Prod OU ID
  Exceptions:
    MinLength: '1'
    MaxLength: '50'
    Type: String
    Description: Exceptions OU ID
    ConstraintDescription: Exceptions OU ID
  RESPCMigration:
    MinLength: '1'
    MaxLength: '50'
    Type: String
    Description: RESPCMigration OU ID
    ConstraintDescription: RESPCMigration OU ID
Resources:
  StacksetPlatformSSMDocuments:
    Type: AWS::CloudFormation::StackSet
    DeletionPolicy: Retain
    Properties:
      TemplateURL:
        Fn::Sub:
          - https://${bucket}.s3.amazonaws.com/${releasefolder}/CloudFormation/SSMDocuments.yaml
          - bucket:
              Ref: releses3bucket
            releasefolder:
              Ref: FolderName
      StackSetName: Nested-OU-Platform-SSMDocuments
      AutoDeployment:
        Enabled: 'true'
        RetainStacksOnAccountRemoval: 'false'
      PermissionModel: SERVICE_MANAGED
      Capabilities:
        - CAPABILITY_NAMED_IAM
      StackInstancesGroup:
        - Regions:
            - us-east-1
            - eu-west-1
            - us-east-2
            - us-west-1
            - us-west-2
            - ap-south-1
            - ap-southeast-2
            - ap-southeast-1
            - eu-central-1
            - eu-west-2
            - eu-north-1
            - ap-northeast-2
            - ap-northeast-1
            - ca-central-1
          DeploymentTargets:
            OrganizationalUnitIds:
              - !Ref RESPCMigration
              - !Ref Prod
              - !Ref NonProd
              - !Ref Exceptions
      OperationPreferences:
        RegionConcurrencyType: 'PARALLEL'
        FailureTolerancePercentage: 90
        MaxConcurrentPercentage: 50
      Tags:
        - Value: 'yes'
          Key: platform_donotdelete