Description: Template to create events rule in Core and Shared OU to send the events to IRM IP Account Event Bus
Parameters:
  IRMAccount:
    Type: String
    Description: IRM IP Account
  IRMEnvironment:
    Description: IRM Environment type.
    Type: String
    AllowedValues:
      - prod
      - uat
      - dev
  AuditAccount:
    Type: String
    Description: Audit Account
Conditions:
  CreateRule: !Equals [!Ref 'AWS::AccountId', !Ref AuditAccount]
  CreateRole: !Equals [!Ref 'AWS::Region', us-east-1]
Resources:
  ComplianceLoggingPolicy:
    Condition: CreateRole
    Type: 'AWS::IAM::ManagedPolicy'
    Properties:
      Description: Policy for Events Rule to send events to IRM IP Account Event Bus
      Path: '/'
      ManagedPolicyName: 'platform_compliance_logging_policy'
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Resource:
              - !Join
                - ''
                - - 'arn:aws:events:*:'
                  - !Ref IRMAccount
                  - ':event-bus/'
                  - !Ref IRMEnvironment
            Action:
              - 'events:PutEvents'
  ComplianceLoggingRole:
    Condition: CreateRole
    Type: 'AWS::IAM::Role'
    Properties:
      Description: Role for EventRule to send events to IRM IP Account Event Bus
      RoleName: 'platform_compliance_logging_role'
      Tags:
        - Value: "yes"
          Key: platform_donotdelete
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - events.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - !Ref ComplianceLoggingPolicy
  ComplianceLoggingConfigEventRule:
    Type: "AWS::Events::Rule"
    Properties:
      Description: Event rule to send Config Events to IRM IP Account Event Bus
      EventPattern:
        source:
          - aws.config
      State: ENABLED
      Name: "platform_compliance_logging_config_events"
      Targets:
        - Arn: !Join
          - ''
          - - 'arn:aws:events:'
            - !Ref AWS::Region
            - ':'
            - !Ref IRMAccount
            - ':event-bus/'
            - !Ref IRMEnvironment
          Id: IRMEventBus
          RoleArn: !Sub 'arn:aws:iam::${AWS::AccountId}:role/platform_compliance_logging_role'
  ComplianceLoggingCloudTrailEventRule:
    Type: "AWS::Events::Rule"
    Properties:
      Description: Event rule to send CloudTrail Events to IRM IP Account Event Bus
      EventPattern:
        source:
          - anything-but:
            - aws.config
            - aws.securityhub
      State: ENABLED
      Name: "platform_compliance_logging_cloudtrail_events"
      Targets:
        - Arn: !Join
          - ''
          - - 'arn:aws:events:'
            - !Ref AWS::Region
            - ':'
            - !Ref IRMAccount
            - ':event-bus/'
            - !Ref IRMEnvironment
          Id: IRMEventBus
          RoleArn: !Sub 'arn:aws:iam::${AWS::AccountId}:role/platform_compliance_logging_role'
  ComplianceLoggingSecurityHubEventRule:
    Condition: CreateRule
    Type: "AWS::Events::Rule"
    Properties:
      Description: Event rule to send Security Hub Events to IRM IP Account Event Bus
      EventPattern:
        source:
          - aws.securityhub
      State: ENABLED
      Name: "platform_compliance_logging_securityhub_events"
      Targets:
        - Arn: !Join
            - ''
            - - 'arn:aws:events:'
              - !Ref AWS::Region
              - ':'
              - !Ref IRMAccount
              - ':event-bus/'
              - !Ref IRMEnvironment
          Id: IRMEventBus
          RoleArn: !Sub 'arn:aws:iam::${AWS::AccountId}:role/platform_compliance_logging_role'