AWSTemplateFormatVersion: 2010-09-09
Description: Create SSM Parameter values in reagion for Cloudwatch Metric Configuration
Resources:
    # -------------------------------------------------------------------------------------------------------------------------------------------------------
  # SCG Framework - Create SSM Parameter values in each region for CloudWatch Metric Configuration
  # -------------------------------------------------------------------------------------------------------------------------------------------------------
  CloudWatchMetricForWindows:
    Type: "AWS::SSM::Parameter"
    Properties:
          Name: "platform_AmazonCloudWatch-windows"
          Type: "String"
          Value: '{
            "logs": {
                "logs_collected": {
                    "files": {
                        "collect_list": [{
                            "file_path": "c:\\ProgramData\\Amazon\\AmazonCloudWatchAgent\\Logs\\amazon-cloudwatch-agent.log",
                            "log_group_name": "amazon-cloudwatch-agent.log"
                        }, {
                            "file_path": "c:\\ProgramData\\Amazon\\AmazonCloudWatchAgent\\Logs\\test.log",
                            "log_group_name": "test.log"
                        }]
                    },
                    "windows_events": {
                        "collect_list": [{
                            "event_format": "text",
                            "event_levels": ["ERROR", "CRITICAL"],
                            "event_name": "System",
                            "log_group_name": "System"
                        }]
                    }
                }
            },
            "metrics": {
                "append_dimensions": {
                    "AutoScalingGroupName": "${aws:AutoScalingGroupName}",
                    "ImageId": "${aws:ImageId}",
                    "InstanceId": "${aws:InstanceId}",
                    "InstanceType": "${aws:InstanceType}"
                },
                "metrics_collected": {
                    "LogicalDisk": {
                        "measurement": ["% Free Space"],
                        "metrics_collection_interval": 60,
                        "resources": ["*"]
                    },
                    "Memory": {
                        "measurement": ["% Committed Bytes In Use"],
                        "metrics_collection_interval": 60
                    },
                    "Paging File": {
                        "measurement": ["% Usage"],
                        "metrics_collection_interval": 60,
                        "resources": ["*"]
                    },
                    "PhysicalDisk": {
                        "measurement": ["% Disk Time"],
                        "metrics_collection_interval": 60,
                        "resources": ["*"]
                    },
                    "Processor": {
                        "measurement": ["% User Time", "% Idle Time", "% Interrupt Time"],
                        "metrics_collection_interval": 60,
                        "resources": ["_Total"]
                    }
                }
            }
        }'
          Description: "SSM Parameter for Windows CloudWatch Configuration"
          Tags:
            platform_donotdelete: yes
  CloudWatchMetricForLinux:
    Type: "AWS::SSM::Parameter"
    Properties:
          Name: "platform_AmazonCloudWatch-Linux"
          Type: "String"
          Value: '{"logs": {
                "logs_collected": {
                    "files": {
                        "collect_list": [
                            {
                                "file_path": "/var/log/**.log",
                                "log_group_name": "linux-os-logs"
                            },
                            {
                                "file_path": "/opt/aws/amazon-cloudwatch-agent/logs/amazon-cloudwatch-agent.log",
                                "log_group_name": "amazon-cloudwatch-agent.log"
                            },
                            {
                                "file_path": "/opt/aws/amazon-cloudwatch-agent/logs/test.log",
                                "log_group_name": "test.log"
                            }
                        ]
                    }
                }
            },
            "metrics": {
                "append_dimensions": {
                    "AutoScalingGroupName": "${aws:AutoScalingGroupName}",
                    "ImageId": "${aws:ImageId}",
                    "InstanceId": "${aws:InstanceId}",
                    "InstanceType": "${aws:InstanceType}"
                },
                "metrics_collected": {
                    "cpu": {
                        "measurement": [
                            "cpu_usage_idle",
                            "cpu_usage_iowait",
                            "cpu_usage_user",
                            "cpu_usage_system"
                        ],
                        "metrics_collection_interval": 60,
                        "resources": [
                            "*"
                        ],
                        "totalcpu": false
                    },
                    "disk": {
                        "measurement": [
                            "used_percent",
                            "inodes_free"
                        ],
                        "metrics_collection_interval": 60,
                        "resources": [
                            "*"
                        ]
                    },
                    "diskio": {
                        "measurement": [
                            "io_time"
                        ],
                        "metrics_collection_interval": 60,
                        "resources": [
                            "*"
                        ]
                    },
                    "mem": {
                        "measurement": [
                            "mem_used_percent"
                        ],
                        "metrics_collection_interval": 60
                    },
                    "swap": {
                        "measurement": [
                            "swap_used_percent"
                        ],
                        "metrics_collection_interval": 60
                    }
                }
            }
        }'
          Description: "SSM Parameter for Linux CloudWatch Configuration."
          Tags:
            platform_donotdelete: yes
  PublicStagingSSM:
    Type: AWS::SSM::Parameter
    Properties:
        Type: String
        Name: SStest
        Value: "Rekhutest"