AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  releses3bucket:
    MinLength: '1'
    MaxLength: '50'
    Type: String
    Description: CI/CD Release bucket
    ConstraintDescription: Relese S3 Bucket
  FolderName:
    MinLength: '1'
    MaxLength: '50'
    Type: String
    Description: CI/CD Release ID
    ConstraintDescription: ReleaseID
  IRMAccount:
    Type: String
    Description: IRM IP Account
  IRMEnvironment:
    Description: IRM Environment type.
    Type: String
    AllowedValues:
      - prod
      - uat
      - dev
  ProdPrivate:
    MinLength: '1'
    MaxLength: '50'
    Type: String
    Description: Prod Private OU ID
    ConstraintDescription: Prod Private OU ID
  NonProdPrivate:
    MinLength: '1'
    MaxLength: '50'
    Type: String
    Description: Non Prod Private OU ID
    ConstraintDescription: Non Prod Private OU ID
  ProdHybrid:
    MinLength: '1'
    MaxLength: '50'
    Type: String
    Description: Prod Hybrid OU ID
    ConstraintDescription: Prod Hybrid OU ID
  NonProdHybrid:
    MinLength: '1'
    MaxLength: '50'
    Type: String
    Description: Non Prod Hybrid OU ID
    ConstraintDescription: Non Prod Hybrid OU ID
Resources:
  StacksetPlatformPrivate:
    Type: AWS::CloudFormation::StackSet
    DeletionPolicy: Retain
    Properties:
      TemplateURL:
        Fn::Sub:
          - https://${bucket}.s3.amazonaws.com/${releasefolder}/CloudFormation/Stackset_Private.yml
          - bucket:
              Ref: releses3bucket
            releasefolder:
              Ref: FolderName
      StackSetName: Nested-OU-Platform-Private
      AutoDeployment:
        Enabled: 'true'
        RetainStacksOnAccountRemoval: 'false'
      PermissionModel: SERVICE_MANAGED
      Capabilities:
        - CAPABILITY_NAMED_IAM
      StackInstancesGroup:
        - Regions:
            - us-east-1
            - eu-west-1
            - us-east-2
            - us-west-1
            - us-west-2
            - ap-south-1
            - ap-southeast-2
            - ap-southeast-1
            - eu-central-1
            - eu-west-2
            - eu-north-1
            - ap-northeast-2
            - ap-northeast-1
            - ca-central-1
          DeploymentTargets:
            OrganizationalUnitIds:
              - !Ref ProdHybrid
              - !Ref ProdPrivate
              - !Ref NonProdHybrid
              - !Ref NonProdPrivate
      OperationPreferences:
        RegionConcurrencyType: 'PARALLEL'
        FailureTolerancePercentage: 100
        MaxConcurrentPercentage: 50
      Tags:
        - Value: 'yes'
          Key: platform_donotdelete
      Parameters:
        - ParameterKey: IRMAccount
          ParameterValue: !Ref IRMAccount
        - ParameterKey: IRMEnvironment
          ParameterValue: !Ref IRMEnvironment