AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  releses3bucket:
    MinLength: '1'
    MaxLength: '50'
    Type: String
    Description: CI/CD Release bucket
    ConstraintDescription: Relese S3 Bucket
  FolderName:
    MinLength: '1'
    MaxLength: '50'
    Type: String
    Description: CI/CD Release ID
    ConstraintDescription: ReleaseID
  PrivateProduction:
    Type: String
    Description: OU ID of the Private Production
  PrivateStaging:
    Type: String
    Description: OU ID of the Private Staging
  PrivateException:
    Type: String
    Description: OU ID of the Private Exception
  PublicProduction:
    Type: String
    Description: OU ID of the Public Production
  PublicStaging:
    Type: String
    Description: OU ID of the Public Staging
  PublicException:
    Type: String
    Description: OU ID of the Public Exception
  ManagedServicesBeAgile:
    Type: String
    Description: OU ID of the Managed Services BeAgile
  DataManagement:
    Type: String
    Description: OU ID of the Data Management
  HybridAccount:
    Type: String
    Description: OU ID of Hybrid Account
  Migration:
    Type: String
    Description: OU ID of Migration Accounts
  platformagentbucket:
    Type: String
    Description: S3 Agent Name
  auditaccount:
    Type: String
    Description: audit account
  masteraccount:
    Type: String
    Description: Master Account
  CoreOU:
    Type: String
    Description: Core OU
  SharedServicesOU:
    Type: String
    Description: Shared Services OU
  ScoreCardDBTableName:
    Type: String
    Description: Enter the DPSOM DL Id
  ScoreCardBucketName:
    Type: String
    Description: Enter the ScoreCardBucketName 
  BucketNameWithOutRegion:
    Type: String
    Description: Enter the BucketNameWithOutRegion 
  platformScoreCardFunctionName:
    Type: String
    Description: Enter ScoreCardVPCBoundLamba name

Resources:
  PlatformDBControlsStackset:
    Type: AWS::CloudFormation::StackSet
    DeletionPolicy: Retain
    Properties:
      TemplateURL:
        Fn::Sub:
          - https://${bucket}.s3.amazonaws.com/${releasefolder}/CloudFormation/Stackset_DBCntrols.yaml
          - bucket:
              Ref: releses3bucket
            releasefolder:
              Ref: FolderName
      StackSetName: platform-dbcontrols-stackset
      AutoDeployment:
        Enabled: 'true'
        RetainStacksOnAccountRemoval: 'false'
      PermissionModel: SERVICE_MANAGED
      Capabilities:
        - CAPABILITY_NAMED_IAM
      StackInstancesGroup:
        - Regions:
            - us-east-1
          DeploymentTargets:
            OrganizationalUnitIds:
              - !Ref PublicException
              - !Ref PublicProduction
              - !Ref Migration
              - !Ref PublicStaging
              - !Ref PrivateProduction
              - !Ref ManagedServicesBeAgile
              - !Ref DataManagement
              - !Ref PrivateException
              - !Ref PrivateStaging
              - !Ref HybridAccount
              - !Ref CoreOU
              - !Ref SharedServicesOU
      OperationPreferences:
        RegionConcurrencyType: 'PARALLEL'
        FailureTolerancePercentage: 90
        MaxConcurrentPercentage: 95
      Parameters:
        - ParameterKey: masteraccount
          ParameterValue: !Ref masteraccount
        - ParameterKey: auditaccount
          ParameterValue: !Ref auditaccount
        - ParameterKey: platformagentbucket
          ParameterValue: !Ref platformagentbucket
        - ParameterKey: ScoreCardBucketName
          ParameterValue: !Ref ScoreCardBucketName
        - ParameterKey: S3BucketName
          ParameterValue: !Ref BucketNameWithOutRegion 
        - ParameterKey: FolderName
          ParameterValue: !Ref FolderName  
        - ParameterKey: ScoreCardDBTableName
          ParameterValue: !Ref ScoreCardDBTableName 
        - ParameterKey: platformScoreCardFunctionName
          ParameterValue: !Ref platformScoreCardFunctionName
      Tags:
        - Value: 'yes'
          Key: platform_donotdelete