AWSTemplateFormatVersion: 2010-09-09
Parameters:
  FolderName:
    ConstraintDescription: FolderName
    Description: CI/CD Release ID
    MaxLength: '50'
    MinLength: '1'
    Type: String
  releases3bucket:
    ConstraintDescription: Release S3 Bucket
    Description: CI/CD Release bucket
    MaxLength: '50'
    MinLength: '1'
    Type: String

Resources:
  AutoTagRole:
    Type: 'AWS::IAM::Role'
    Properties:
      RoleName: !Sub 'platform_stackset_AutoTagging_role_${AWS::Region}' 
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - !Ref PlatformAutTagPolicy

  PlatformAutTagPolicy:
    Type: 'AWS::IAM::ManagedPolicy'
    Properties:
      Description: Policy for creating a test database
      Path: /
      ManagedPolicyName: !Sub 'platform_Autotagging_role_policy_${AWS::Region}'  
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - ssm:GetParametersByPath
              - s3:DeleteJobTagging
              - s3:DeleteObjectTagging
              - s3:DeleteObjectVersionTagging
              - s3:DeleteStorageLensConfigurationTagging
              - s3:PutBucketTagging
              - s3:PutJobTagging
              - s3:PutObjectTagging
              - s3:PutObjectVersionTagging
              - s3:PutStorageLensConfigurationTagging
              - s3:ReplicateTags
              - s3:GetObjectTagging
              - s3:GetBucketTagging
              - s3:GetObjectVersionTagging
              - ec2:DescribeTags
              - ec2:CreateTags
              - ec2:DeleteTags
              - backup:ListTags
              - backup:TagResource
              - backup:UntagResource
              - cloudfront:ListTagsForResource
              - cloudfront:CreateDistributionWithTags
              - cloudfront:CreateStreamingDistributionWithTags
              - cloudfront:TagResource
              - cloudfront:UntagResource
              - cloudwatch:ListTagsForResource
              - cloudwatch:TagResource
              - cloudwatch:UntagResource
              - elasticloadbalancing:DescribeTags
              - elasticloadbalancing:AddTags
              - elasticloadbalancing:RemoveTags
              - elasticloadbalancing:DescribeTargetGroupAttributes
              - elasticloadbalancing:DescribeTargetGroups
              - events:ListTagsForResource
              - events:TagResource
              - events:UntagResource
              - guardduty:ListTagsForResource
              - guardduty:TagResource
              - guardduty:UntagResource
              - iam:TagInstanceProfile
              - iam:TagMFADevice
              - iam:TagOpenIDConnectProvider
              - iam:TagPolicy
              - iam:TagRole
              - iam:TagSAMLProvider
              - iam:TagServerCertificate
              - iam:TagUser
              - iam:UntagInstanceProfile
              - iam:UntagMFADevice
              - iam:UntagOpenIDConnectProvider
              - iam:UntagPolicy
              - iam:UntagRole
              - iam:UntagSAMLProvider
              - iam:UntagServerCertificate
              - iam:UntagUser
              - logs:ListTagsLogGroup
              - logs:TagLogGroup
              - logs:UntagLogGroup
              - logs:ListLogDeliveries
              - logs:ListTagsLogGroup
              - logs:FilterLogEvents
              - logs:GetLogDelivery
              - logs:GetLogEvents
              - logs:GetLogGroupFields
              - logs:GetLogRecord
              - logs:CreateLogDelivery
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutDestination
              - logs:PutDestinationPolicy
              - logs:PutLogEvents
              - logs:UpdateLogDelivery
              - securityhub:ListTagsForResource
              - securityhub:TagResource
              - securityhub:UntagResource
              - sqs:ListQueueTags
              - sqs:TagQueue
              - sqs:UntagQueue
              - ssm:ListTagsForResource
              - ssm:AddTagsToResource
              - ssm:RemoveTagsFromResource
              - sns:ListTagsForResource
              - sns:TagResource
              - sns:UntagResource
              - budgets:ViewBudget
              - budgets:ModifyBudget
              - redshift:DeleteTags
              - redshift:CreateTags
              - redshift:DescribeTags
              - dynamodb:UntagResource
              - dynamodb:TagResource
              - dynamodb:ListTagsOfResource
              - acm:AddTagsToCertificate
              - acm:RemoveTagsFromCertificate
              - lambda:TagResource
              - lambda:UntagResource
              - lambda:ListTags
              - cloudtrail:AddTags
              - cloudtrail:RemoveTags
              - cloudtrail:ListTags
              - config:TagResource
              - config:UntagResource
              - config:ListTagsForResource
              - config:PutEvaluations
              - access-analyzer:ListTagsForResource
              - access-analyzer:TagResource
              - access-analyzer:UntagResource
              - cloudformation:TagResource
              - cloudformation:UntagResource
              - rds:AddTagsToResource
              - rds:RemoveTagsFromResource
              - rds:ListTagsForResource
              - rds:DescribeDBInstances
            Resource: "*"

  FunctionToTagBusinessResources:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: platform_AutoTag
      Code:
        S3Bucket:
          Fn::Sub:
          - '${releaseBucket}${AWS::Region}'
          - {releaseBucket: !Ref releases3bucket}
        S3Key:
          Fn::Sub:
          - '${releasefolder}/platform_AutoTag.zip'
          - {releasefolder: !Ref FolderName}
      Description: Tag the Resources according to config rule change
      Handler: platform_AutoTag.lambda_handler
      MemorySize: 1024
      Role: !GetAtt AutoTagRole.Arn
      Runtime: python3.8
      Timeout: 900

  ScheduledRuleAutoTag:
    Type: "AWS::Events::Rule"
    Properties:
      Name: platform-AutoTagEvent
      Description: "Event triggered using config rule for Auto tag"
      EventPattern:
        detail-type:
        - Config Rules Compliance Change
        source:
        - aws.config
        detail:
          configRuleName:
          - platform_Auto-Tag
          messageType:
          - ComplianceChangeNotification
      State: "ENABLED"
      Targets:
        - Arn: !GetAtt FunctionToTagBusinessResources.Arn
          Id: "TargetFunctionV1"

  PermissionForAutoTagscheduler:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref FunctionToTagBusinessResources
      Action: "lambda:InvokeFunction"
      Principal: "events.amazonaws.com"
      SourceArn:
        Fn::GetAtt:
          - "ScheduledRuleAutoTag"
          - "Arn"

  FunctionToTagBusinessResources1:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: platform_AutoBackupTag
      Code:
        S3Bucket:
          Fn::Sub:
          - '${releaseBucket}${AWS::Region}'
          - {releaseBucket: !Ref releases3bucket}
        S3Key:
          Fn::Sub:
          - '${releasefolder}/platform_AutoBackupTag.zip'
          - {releasefolder: !Ref FolderName}
      Description: Tag the Resources according to config rule change
      Handler: platform_AutoBackupTag.lambda_handler
      MemorySize: 1024
      Role: !GetAtt AutoTagRole.Arn
      Runtime: python3.8
      Timeout: 900

  ScheduledRuleAutoTag1:
    Type: "AWS::Events::Rule"
    Properties:
      Name: platform-AutoBackupTagEvent
      Description: "Event triggered using config rule for Auto tag"
      EventPattern:
        detail-type:
        - Config Rules Compliance Change
        source:
        - aws.config
        detail:
          configRuleName:
          - platform_Auto-Backup-Tag
          messageType:
          - ComplianceChangeNotification
      State: "ENABLED"
      Targets:
        - Arn: !GetAtt FunctionToTagBusinessResources1.Arn
          Id: "TargetFunctionV1"

  PermissionForAutoTagscheduler1:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref FunctionToTagBusinessResources1
      Action: "lambda:InvokeFunction"
      Principal: "events.amazonaws.com"
      SourceArn:
        Fn::GetAtt:
          - "ScheduledRuleAutoTag1"
          - "Arn"
